services:
  postgres:
    image: paradedb/paradedb:latest
    container_name: paperboy-parade
    environment:
      POSTGRES_DB: paperboy
      POSTGRES_USER: minhhieu
      POSTGRES_PASSWORD: minhhieu888
    ports:
      - "5436:5432"
    volumes:
      - ../Project Paperboy/data/postgres:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  redis:
    image: redis:7
    container_name: paperboy-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:


