services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: paperboy-pgsql
    environment:
      POSTGRES_DB: paperboy
      POSTGRES_USER: minhhieu
      POSTGRES_PASSWORD: minhhieu888
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: elasticsearch_container
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  esdata:
