services:
  postgres:
    image: paradedb/paradedb:latest
    container_name: paperboy-parade
    environment:
      POSTGRES_DB: paperboy
      POSTGRES_USER: minhhieu
      POSTGRES_PASSWORD: minhhieu888
    ports:
      - "5436:5432"
    volumes:
      - ../Project Paperboy/data/postgres:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

